name: Import to Vercel

on:
  workflow_dispatch: # 手動觸發
    inputs:
      project_name:
        description: "Enter project name"
        required: true
        default: "my-default-project"

jobs:
  import-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Import GitHub Repository to Vercel
        env:
          PROJECT_NAME: ${{ github.event.inputs.project_name }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_ACCOUNT_KEY }}
          REPO_URL: ${{ github.repository }} # 自動獲取當前 GitHub 儲存庫名稱
          ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          curl -X POST https://api.vercel.com/v9/projects \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "'"$PROJECT_NAME"'",
              "gitRepository": {
                "type": "github",
                "repo": "'"$REPO_URL"'"
              },
              "framework": "node"
            }'
