name: Import to Vercel

on:
  workflow_dispatch: # 手動觸發
    inputs:
      project_name:
        description: "Enter project name"
        required: true
        default: "my-default-project"

jobs:
  import-vercel:
    runs-on: ubuntu-latest
    steps:
      # 檢出專案代碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 安裝 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.15" # 你的 Node.js 版本

      # 安裝依賴
      - name: Install dependencies
        run: npm install

      # 運行 Vercel build
      - name: Run Vercel Build (local build simulation)
        run: |
          echo "Running vercel build"
          npx vercel build --token ${{ secrets.VERCEL_ACCOUNT_KEY }} \
            --scope ${{ secrets.VERCEL_ORG_NAME }} --yes

      # 如果構建成功，部署到 Vercel
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel"
          echo '{"name": "${{ github.event.inputs.project_name }}"}' > vercel.json
          npx vercel --prod --token ${{ secrets.VERCEL_ACCOUNT_KEY }} \
            --scope ${{ secrets.VERCEL_ORG_NAME }} --yes
