name: Import to Vercel

on:
  workflow_dispatch: # 手動觸發
    inputs:
      project_name:
        description: "Enter project name"
        required: true
        default: "my-default-project"

jobs:
  import-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Import GitHub Repository to Vercel
        run: |
          npx vercel --prod --token ${{ secrets.VERCEL_ACCOUNT_KEY }} \
          --org-id ${{ secrets.VERCEL_ORG_ID }} \
          --project-name ${{ github.event.inputs.project_name }}
