name: Remove from Vercel

on:
  workflow_dispatch: # 手動觸發

jobs:
  remove:
    runs-on: ubuntu-latest

    steps:
      - name: Remove project from Vercel
        run: |
          curl -X DELETE "https://api.vercel.com/v9/projects/${{ secrets.VERCEL_PROJECT_ID }}" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
